language: python
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py35
    - TOXENV=py36

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libgdal1-dev

install:
  - pip install tox
  - pip install coveralls

script:
  tox

after_success:
  coveralls
