environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36

shallow_clone: true

install:
  - set SDK=release-1800-x64
  - set SDK_ZIP=%SDK%-dev.zip
  - set SDK_URL=http://download.gisinternals.com/sdk/downloads/%SDK_ZIP%
  - echo "%SDK_ZIP%"
  - echo "%SDK_URL%"
  - mkdir sdk
  - cd sdk
  - appveyor DownloadFile "%SDK_URL%"
  - 7z x "%SDK_ZIP%" > nul
  - cd ..
  - set SDK_PREFIX=%CD%\sdk\%SDK%
  - set SDK_INC=%CD%\sdk\%SDK%\include
  - set SDK_LIB=%CD%\sdk\%SDK%\lib
  - set SDK_BIN=%CD%\sdk\%SDK%\bin
  - set PATH=%SDK_BIN%;%PATH%
  - set GDAL_DATA=%SDK_BIN%\gdal-data
  - 'python -m pip install wheel'
  - 'python -m pip install tox'

build: off

test_script:
  - echo test_script
  - 'python -m tox'

after_test:
  - 'python setup.py bdist_wheel'

artifacts:
  - path: dist\*

deploy: off

