environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "27"
      PYTHON_ARCH: "32"
      WIN_ARCH: "win32"
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "35"
      PYTHON_ARCH: "32"
      WIN_ARCH: "win32"
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "36"
      PYTHON_ARCH: "32"
      WIN_ARCH: "win32"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "27"
      PYTHON_ARCH: "64"
      WIN_ARCH: "win_amd64"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "35"
      PYTHON_ARCH: "64"
      WIN_ARCH: "win_amd64"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "36"
      PYTHON_ARCH: "64"
      WIN_ARCH: "win_amd64"

shallow_clone: true

install:
  - set GDAL_VERSION=2.1.3
  - set LXML_VERSION=3.7.3
  - set PYTHON_BIN_VER="cp%PYTHON_VERSION%-cp%PYTHON_VERSION%m-%WIN_ARCH%"
  - set GDAL_WHL="test_deps/GDAL-%GDAL_VERSION%-%PYTHON_BIN_VER%.whl"
  - set LXML_WHL="test_deps/lxml-%LXML_VERSION%-%PYTHON_BIN_VER%.whl"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -U pip"
  - "%PYTHON%\\python.exe -m pip install %GDAL_WHL%"
  - "%PYTHON%\\python.exe -m pip install %LXML_WHL%"
  - "%PYTHON%\\python.exe -m pip install -rrequirements.txt -rrequirements-dev.txt"

build: off

test_script:
  - echo test_script
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

deploy: off

